In [11]:
# FOR IGNORING FUTURE WARNINGS AND ERROR MESSAGES ----

import warnings

warnings.filterwarnings('ignore')

In [1]:
# IMPORTING ALL NECESAARY LIBRARIES ----

#FOR DATA ANALYSING --
import pandas as pd
import numpy as np

#FOR VISUALISATION --
import matplotlib.pyplot as plt
import seaborn as sns

# FOR FEATURE ENCODING --
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# FOR TRAINING & TESTING --
from sklearn.model_selection import train_test_split

# FOR MODEL BUILDING --
from sklearn.ensemble import RandomForestClassifier

# FOR MODEL EVALUATION --
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# FOR SAVING THE MODEL BUILD --
import joblib


print('ALL NECESSARY LIBRARIES ARE IMPORTED SUCCESSFULLY: ')
print('🏅🏅🏅🏅')

ALL NECESSARY LIBRARIES ARE IMPORTED SUCCESSFULLY:
🏅🏅🏅🏅

In [6]:
# FOR IMPORTING THE DATA --

df = pd.read_csv("C:\\Users\\mohit\\OneDrive\\Desktop\\Calmify AI\\Calmify_AI\\Calmify_AI\\datasets\\StressLevelDataset.csv")

df.head()

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,basic_needs,academic_performance,study_load,teacher_student_relationship,future_career_concerns,social_support,peer_pressure,extracurricular_activities,bullying,stress_level
0,14,20,0,11,2,1,2,4,2,3,...,2,3,2,3,3,2,3,3,2,1
1,15,8,1,15,5,3,1,4,3,1,...,2,1,4,1,5,1,4,5,5,2
2,12,18,1,14,2,1,2,2,2,2,...,2,2,3,3,2,2,3,2,2,1
3,16,12,1,15,4,3,1,3,4,2,...,2,2,4,1,4,1,4,4,5,2
4,16,28,0,7,2,3,5,1,3,2,...,3,4,3,1,2,1,5,0,5,1

In [8]:
# for SHAPE OF DATASET --

print(df.shape)

(1100, 21)

In [9]:
# FOR GETTING INFO. OF DATASET --

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   anxiety_level                 1100 non-null   int64
 1   self_esteem                   1100 non-null   int64
 2   mental_health_history         1100 non-null   int64
 3   depression                    1100 non-null   int64
 4   headache                      1100 non-null   int64
 5   blood_pressure                1100 non-null   int64
 6   sleep_quality                 1100 non-null   int64
 7   breathing_problem             1100 non-null   int64
 8   noise_level                   1100 non-null   int64
 9   living_conditions             1100 non-null   int64
 10  safety                        1100 non-null   int64
 11  basic_needs                   1100 non-null   int64
 12  academic_performance          1100 non-null   int64
 13  study_load                    1100 non-null   int64
 14  teacher_student_relationship  1100 non-null   int64
 15  future_career_concerns        1100 non-null   int64
 16  social_support                1100 non-null   int64
 17  peer_pressure                 1100 non-null   int64
 18  extracurricular_activities    1100 non-null   int64
 19  bullying                      1100 non-null   int64
 20  stress_level                  1100 non-null   int64
dtypes: int64(21)
memory usage: 180.6 KB
None

In [15]:
# FOR GETTING NULL VALUES --

print(df.isnull().sum())


missing_percentage = (df.isnull().sum()/len(df))*100

print(missing_percentage)

anxiety_level                   0
self_esteem                     0
mental_health_history           0
depression                      0
headache                        0
blood_pressure                  0
sleep_quality                   0
breathing_problem               0
noise_level                     0
living_conditions               0
safety                          0
basic_needs                     0
academic_performance            0
study_load                      0
teacher_student_relationship    0
future_career_concerns          0
social_support                  0
peer_pressure                   0
extracurricular_activities      0
bullying                        0
stress_level                    0
dtype: int64
anxiety_level                   0.0
self_esteem                     0.0
mental_health_history           0.0
depression                      0.0
headache                        0.0
blood_pressure                  0.0
sleep_quality                   0.0
breathing_problem               0.0
noise_level                     0.0
living_conditions               0.0
safety                          0.0
basic_needs                     0.0
academic_performance            0.0
study_load                      0.0
teacher_student_relationship    0.0
future_career_concerns          0.0
social_support                  0.0
peer_pressure                   0.0
extracurricular_activities      0.0
bullying                        0.0
stress_level                    0.0
dtype: float64

In [13]:
# FOR TOTAL SIMILAR VALUES --

print(df["stress_level"].value_counts())

stress_level
0    373
2    369
1    358
Name: count, dtype: int64

In [14]:
# for all the columns in dataset --

print("columns are: ✅✅")
print(df.columns.tolist())

columns are: ✅✅
['anxiety_level', 'self_esteem', 'mental_health_history', 'depression', 'headache', 'blood_pressure', 'sleep_quality', 'breathing_problem', 'noise_level', 'living_conditions', 'safety', 'basic_needs', 'academic_performance', 'study_load', 'teacher_student_relationship', 'future_career_concerns', 'social_support', 'peer_pressure', 'extracurricular_activities', 'bullying', 'stress_level']

In [17]:
# FOR FINDING DUPLICATES --

a = df.duplicated().sum()

if a == 0 :
    print('NO DUPLICATES:😁')

else:
    print(a)

df.drop_duplicates(inplace=True)

NO DUPLICATES:😁

In [18]:
# FOR SUMMARY OF DAYASET --

print('summary of datasrt is: ')

print("       ")

df.describe()

summary of datasrt is:

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,basic_needs,academic_performance,study_load,teacher_student_relationship,future_career_concerns,social_support,peer_pressure,extracurricular_activities,bullying,stress_level
count,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,...,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000
mean,11.063636,17.777273,0.492727,12.555455,2.508182,2.181818,2.660000,2.753636,2.649091,2.518182,...,2.772727,2.772727,2.621818,2.648182,2.649091,1.881818,2.734545,2.767273,2.617273,0.996364
std,6.117558,8.944599,0.500175,7.727008,1.409356,0.833575,1.548383,1.400713,1.328127,1.119208,...,1.433761,1.414594,1.315781,1.384579,1.529375,1.047826,1.425265,1.417562,1.530958,0.821673
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,11.000000,0.000000,6.000000,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,1.000000,0.000000
50%,11.000000,19.000000,0.000000,12.000000,3.000000,2.000000,2.500000,3.000000,3.000000,2.000000,...,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.500000,3.000000,1.000000
75%,16.000000,26.000000,1.000000,19.000000,3.000000,3.000000,4.000000,4.000000,3.000000,3.000000,...,4.000000,4.000000,3.000000,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,2.000000
max,21.000000,30.000000,1.000000,27.000000,5.000000,3.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,3.000000,5.000000,5.000000,5.000000,2.000000