# <b><i><u>STUDENT MENTAL HEALTH SURVEY </U>----</B></I>

In [1]:
# FOR PATH RECOGNISION ----

from pathlib import Path

print("Current Folder:")
print(Path.cwd())

print("\nParent:")
print(Path.cwd().parent)

Current Folder:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\students_mental_health_survey

Parent:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks

In [2]:
# IGNORE WARNING --

import warnings

warnings.filterwarnings("ignore")

In [3]:
# IMPORTING ALL THE NECESSARY LIBRARIES --

# Data Handling

import pandas as pd
import numpy as np

# Visualization

import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler,
    MinMaxScaler
)

# Train Test Split

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    cross_val_score
)

# Models

from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor
)

from xgboost import (
    XGBClassifier,
    XGBRegressor
)

# Evaluation

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Model Saving

import joblib

# Display

pd.set_option(
    "display.max_columns",
    None
)

sns.set_style("whitegrid")

print("all the necessary libraries are imported sucessfully:")
print("🎉🎉🎉🎉")

all the necessary libraries are imported sucessfully:
🎉🎉🎉🎉

In [4]:
# DISPLAY SETTINGS --

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
sns.set_style("whitegrid")

In [5]:
# LOADING DATASET --

# current folder = Calmify_AI/notebooks/mental_health_status
CURRENT_DIR = Path.cwd()

# Calmify_AI root folder
BASE_DIR = CURRENT_DIR.parents[1]

# dataset path = Calmify_AI/datasets/mental_health_dataset.csv
DATASET_PATH = BASE_DIR / "datasets" / "students_mental_health_survey.csv"

df = pd.read_csv(DATASET_PATH)

print("Dataset loaded successfully:✅✅✅✅")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully:✅✅✅✅
Shape: (7022, 20)

,Age,Course,Gender,CGPA,Stress_Level,Depression_Score,Anxiety_Score,Sleep_Quality,Physical_Activity,Diet_Quality,Social_Support,Relationship_Status,Substance_Use,Counseling_Service_Use,Family_History,Chronic_Illness,Financial_Stress,Extracurricular_Involvement,Semester_Credit_Load,Residence_Type
0,25,Others,Male,3.56,3,3,2,Good,Moderate,Good,Moderate,Married,Never,Never,No,No,2,Moderate,17,On-Campus
1,24,Engineering,Female,2.44,0,3,0,Average,Low,Average,Low,Single,Occasionally,Occasionally,No,No,3,Low,27,On-Campus
2,19,Business,Female,3.74,4,0,3,Good,Low,Average,Moderate,In a Relationship,Never,Occasionally,No,No,4,High,15,On-Campus
3,19,Computer Science,Male,3.65,2,1,0,Average,Low,Average,Moderate,Single,NaN,Never,No,No,4,Moderate,20,Off-Campus
4,18,Business,Male,3.40,3,3,4,Good,Low,Average,High,Married,Never,Never,No,Yes,0,High,23,On-Campus

In [6]:
# informaion --

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7022 entries, 0 to 7021
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          7022 non-null   int64
 1   Course                       7022 non-null   object
 2   Gender                       7022 non-null   object
 3   CGPA                         7010 non-null   float64
 4   Stress_Level                 7022 non-null   int64
 5   Depression_Score             7022 non-null   int64
 6   Anxiety_Score                7022 non-null   int64
 7   Sleep_Quality                7022 non-null   object
 8   Physical_Activity            7022 non-null   object
 9   Diet_Quality                 7022 non-null   object
 10  Social_Support               7022 non-null   object
 11  Relationship_Status          7022 non-null   object
 12  Substance_Use                7007 non-null   object
 13  Counseling_Service_Use       7022 non-null   object
 14  Family_History               7022 non-null   object
 15  Chronic_Illness              7022 non-null   object
 16  Financial_Stress             7022 non-null   int64
 17  Extracurricular_Involvement  7022 non-null   object
 18  Semester_Credit_Load         7022 non-null   int64
 19  Residence_Type               7022 non-null   object
dtypes: float64(1), int64(6), object(13)
memory usage: 1.1+ MB

In [7]:
# columns of dataset --

print("\nColumns:")
print(df.columns.tolist())

Columns:
['Age', 'Course', 'Gender', 'CGPA', 'Stress_Level', 'Depression_Score', 'Anxiety_Score', 'Sleep_Quality', 'Physical_Activity', 'Diet_Quality', 'Social_Support', 'Relationship_Status', 'Substance_Use', 'Counseling_Service_Use', 'Family_History', 'Chronic_Illness', 'Financial_Stress', 'Extracurricular_Involvement', 'Semester_Credit_Load', 'Residence_Type']

In [8]:
# description of dataset --

df.describe(include="all")

,Age,Course,Gender,CGPA,Stress_Level,Depression_Score,Anxiety_Score,Sleep_Quality,Physical_Activity,Diet_Quality,Social_Support,Relationship_Status,Substance_Use,Counseling_Service_Use,Family_History,Chronic_Illness,Financial_Stress,Extracurricular_Involvement,Semester_Credit_Load,Residence_Type
count,7022.000000,7022,7022,7010.00000,7022.000000,7022.000000,7022.000000,7022,7022,7022,7022,7022,7007,7022,7022,7022,7022.000000,7022,7022.000000,7022
unique,NaN,6,2,NaN,NaN,NaN,NaN,3,3,3,3,3,3,3,2,2,NaN,3,NaN,3
top,NaN,Medical,Male,NaN,NaN,NaN,NaN,Good,Moderate,Average,Moderate,Single,Never,Never,No,No,NaN,Moderate,NaN,On-Campus
freq,NaN,2105,3547,NaN,NaN,NaN,NaN,3589,3521,4268,3470,3574,5903,4263,4866,6678,NaN,3440,NaN,2815
mean,23.003418,NaN,NaN,3.49127,2.427941,2.254486,2.300484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.453005,NaN,22.010538,NaN
std,3.853978,NaN,NaN,0.28742,1.638408,1.625193,1.624305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.708995,NaN,4.358380,NaN
min,18.000000,NaN,NaN,2.44000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,15.000000,NaN
25%,20.000000,NaN,NaN,3.29000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,18.000000,NaN
50%,22.000000,NaN,NaN,3.50000,2.000000,2.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,22.000000,NaN
75%,25.000000,NaN,NaN,3.70000,4.000000,3.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,26.000000,NaN
max,35.000000,NaN,NaN,4.00000,5.000000,5.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,29.000000,NaN

In [9]:
# standardising columns --

df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

print(df.columns.tolist())

['age', 'course', 'gender', 'cgpa', 'stress_level', 'depression_score', 'anxiety_score', 'sleep_quality', 'physical_activity', 'diet_quality', 'social_support', 'relationship_status', 'substance_use', 'counseling_service_use', 'family_history', 'chronic_illness', 'financial_stress', 'extracurricular_involvement', 'semester_credit_load', 'residence_type']

In [10]:
# DUPLICATES --

duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [11]:
# MISSING VALUES --

missing = df.isnull().sum().sort_values(ascending=False)
missing[missing > 0]

substance_use    15
cgpa             12
dtype: int64

In [12]:
# HANDLING MISSING VALUES --

df["cgpa"] = df["cgpa"].fillna(df["cgpa"].median())

df["substance_use"] = df["substance_use"].fillna(df["substance_use"].mode()[0])

In [13]:
df.isnull().sum()

age                            0
course                         0
gender                         0
cgpa                           0
stress_level                   0
depression_score               0
anxiety_score                  0
sleep_quality                  0
physical_activity              0
diet_quality                   0
social_support                 0
relationship_status            0
substance_use                  0
counseling_service_use         0
family_history                 0
chronic_illness                0
financial_stress               0
extracurricular_involvement    0
semester_credit_load           0
residence_type                 0
dtype: int64

# <B><I><U>ENCODING </U> ----</B></I>

In [14]:
# CATEGORICAL COLUMNS --

categorical_cols = df.select_dtypes(include="object").columns.tolist()

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- course ---
course
Medical             2105
Law                 1385
Engineering         1072
Computer Science    1028
Business             717
Others               715
Name: count, dtype: int64

--- gender ---
gender
Male      3547
Female    3475
Name: count, dtype: int64

--- sleep_quality ---
sleep_quality
Good       3589
Average    2735
Poor        698
Name: count, dtype: int64

--- physical_activity ---
physical_activity
Moderate    3521
Low         2091
High        1410
Name: count, dtype: int64

--- diet_quality ---
diet_quality
Average    4268
Good       1385
Poor       1369
Name: count, dtype: int64

--- social_support ---
social_support
Moderate    3470
High        2176
Low         1376
Name: count, dtype: int64

--- relationship_status ---
relationship_status
Single               3574
In a Relationship    2079
Married              1369
Name: count, dtype: int64

--- substance_use ---
substance_use
Never           5918
Occasionally     699
Frequently       405
Name: count, dtype: int64

--- counseling_service_use ---
counseling_service_use
Never           4263
Occasionally    2081
Frequently       678
Name: count, dtype: int64

--- family_history ---
family_history
No     4866
Yes    2156
Name: count, dtype: int64

--- chronic_illness ---
chronic_illness
No     6678
Yes     344
Name: count, dtype: int64

--- extracurricular_involvement ---
extracurricular_involvement
Moderate    3440
Low         2164
High        1418
Name: count, dtype: int64

--- residence_type ---
residence_type
On-Campus      2815
Off-Campus     2788
With Family    1419
Name: count, dtype: int64

In [15]:
# CLEAN TEXT COLUMNS --

for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip()

In [16]:
# ORDINAL MAPPING --

# quality / level mappings
quality_map = {
    "Poor": 0,
    "Average": 1,
    "Good": 2
}

activity_map = {
    "Low": 0,
    "Moderate": 1,
    "High": 2
}

support_map = {
    "Low": 0,
    "Moderate": 1,
    "High": 2
}

substance_map = {
    "Never": 0,
    "Occasionally": 1,
    "Frequently": 2
}

In [17]:
# ORDINAL ENCODING --

df["sleep_quality"] = df["sleep_quality"].map(quality_map)
df["physical_activity"] = df["physical_activity"].map(activity_map)
df["diet_quality"] = df["diet_quality"].map(quality_map)
df["social_support"] = df["social_support"].map(support_map)
df["substance_use"] = df["substance_use"].map(substance_map)
df["counseling_service_use"] = df["counseling_service_use"].map(substance_map)
df["extracurricular_involvement"] = df["extracurricular_involvement"].map(activity_map)

In [18]:
# BINARY COLUMNS --

binary_map = {
    "No": 0,
    "Yes": 1
}

df["family_history"] = df["family_history"].map(binary_map)
df["chronic_illness"] = df["chronic_illness"].map(binary_map)

In [19]:
# GENDER --

gender_map = {
    "Male": 1,
    "Female": 0
}

df["gender"] = df["gender"].map(gender_map)

# unknown / others -> 2
df["gender"] = df["gender"].fillna(2).astype(int)

In [20]:
# RELATIONSHIP STATUS --

relationship_map = {
    "Single": 0,
    "In a Relationship": 1,
    "Married": 2
}

df["relationship_status"] = df["relationship_status"].map(relationship_map)

In [21]:
# RESIDENCE TYPE--

# Check unique values first
print(df["residence_type"].value_counts(dropna=False))

residence_map = {
    "On-Campus": 0,
    "Off-Campus": 1,
    "With Family": 2,
    "Hostel": 0,          # fallback if present
    "Home": 2             # fallback if present
}

df["residence_type"] = df["residence_type"].map(residence_map)

residence_type
On-Campus      2815
Off-Campus     2788
With Family    1419
Name: count, dtype: int64

In [22]:
# COURSE --

course_dummies = pd.get_dummies(
    df["course"],
    prefix="course",
    drop_first=True
)

df = pd.concat([df, course_dummies], axis=1)
df.drop(columns=["course"], inplace=True)

print("Shape after course encoding:", df.shape)

Shape after course encoding: (7022, 24)

In [23]:
df.isnull().sum()[df.isnull().sum() > 0]

Series([], dtype: int64)

# <B><I><U>FEATURE ENGINEERING</U> ----</B></I>

In [24]:
# Mental health combined score --

df["mental_health_score"] = (
    df["depression_score"] + df["anxiety_score"]
)

In [25]:
# WELLNESS SCORE --

df["wellness_score"] = (
    df["sleep_quality"] +
    df["physical_activity"] +
    df["diet_quality"] +
    df["social_support"] +
    df["extracurricular_involvement"]
)

In [26]:
# ACADEMIC LOAD --

# cgpa ko reverse stress signal ke saath use karenge:
# lower cgpa -> more academic concern
df["cgpa_risk"] = 4.0 - df["cgpa"]

df["academic_load_score"] = (
    df["cgpa_risk"] +
    df["semester_credit_load"] / 10 +
    df["financial_stress"]
)

In [27]:
# HEALTH RISK --

df["health_risk_score"] = (
    df["family_history"] +
    df["chronic_illness"] +
    df["substance_use"] +
    df["counseling_service_use"]
)

In [28]:
# SOCIAL RISK --

# lower support / lower involvement / difficult relationship can add stress
df["social_risk_score"] = (
    (2 - df["social_support"]) +
    (2 - df["extracurricular_involvement"]) +
    df["relationship_status"]
)

In [29]:
# OVERALL RISK --

df["overall_risk_score"] = (
    df["mental_health_score"] +
    df["academic_load_score"] +
    df["health_risk_score"] +
    df["social_risk_score"]
)

In [30]:
# STRESS VULNARABILITY --

df["stress_vulnerability_score"] = (
    df["depression_score"] +
    df["anxiety_score"] +
    df["financial_stress"] +
    (2 - df["sleep_quality"])
)

In [31]:
# FATURE ENGINEERED DATASET --

print("Shape after feature engineering:", df.shape)
df.head()

Shape after feature engineering: (7022, 32)

,age,gender,cgpa,stress_level,depression_score,anxiety_score,sleep_quality,physical_activity,diet_quality,social_support,relationship_status,substance_use,counseling_service_use,family_history,chronic_illness,financial_stress,extracurricular_involvement,semester_credit_load,residence_type,course_Computer Science,course_Engineering,course_Law,course_Medical,course_Others,mental_health_score,wellness_score,cgpa_risk,academic_load_score,health_risk_score,social_risk_score,overall_risk_score,stress_vulnerability_score
0,25,1,3.56,3,3,2,2,1,2,1,2,0,0,0,0,2,1,17,0,False,False,False,False,True,5,7,0.44,4.14,0,4,13.14,7
1,24,0,2.44,0,3,0,1,0,1,0,0,1,1,0,0,3,0,27,0,False,True,False,False,False,3,2,1.56,7.26,2,4,16.26,7
2,19,0,3.74,4,0,3,2,0,1,1,1,0,1,0,0,4,2,15,0,False,False,False,False,False,3,6,0.26,5.76,1,2,11.76,7
3,19,1,3.65,2,1,0,1,0,1,1,0,0,0,0,0,4,1,20,1,True,False,False,False,False,1,4,0.35,6.35,0,2,9.35,6
4,18,1,3.40,3,3,4,2,0,1,2,2,0,0,0,1,0,2,23,0,False,False,False,False,False,7,7,0.60,2.90,1,2,12.90,7

In [32]:
# TARGET

df["stress_level"].value_counts().sort_index()

stress_level
0    1098
1    1233
2    1279
3    1405
4     992
5    1015
Name: count, dtype: int64

In [33]:
# CORRELATION WITH TARGET --

numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
numeric_cols

corr_with_target = (
    df[numeric_cols]
    .corr()["stress_level"]
    .sort_values(ascending=False)
)

corr_with_target

stress_level                   1.000000
health_risk_score              0.026962
counseling_service_use         0.021049
family_history                 0.019478
chronic_illness                0.017232
residence_type                 0.016723
sleep_quality                  0.006914
physical_activity              0.006019
cgpa                           0.005110
wellness_score                 0.004589
extracurricular_involvement    0.004461
relationship_status            0.002191
gender                         0.002103
social_risk_score              0.001488
substance_use                  0.000854
financial_stress              -0.001388
diet_quality                  -0.002477
academic_load_score           -0.003500
social_support                -0.004749
cgpa_risk                     -0.005110
semester_credit_load          -0.005558
age                           -0.019901
overall_risk_score            -0.031772
anxiety_score                 -0.035802
depression_score              -0.043313
stress_vulnerability_score    -0.046576
mental_health_score           -0.056455
Name: stress_level, dtype: float64

In [34]:
# DROPING COLUMNS --

drop_cols = [
    "gender",                  
    "health_risk_score",     
    "social_risk_score",       
    "overall_risk_score",      
    "cgpa_risk"                
]

In [35]:
drop_cols = [
    "mental_health_score",
    "stress_vulnerability_score",
    "academic_load_score",
    "wellness_score"
]

In [36]:

# only drop columns that actually exist
drop_cols = [col for col in drop_cols if col in df.columns]

df_reduced = df.drop(columns=drop_cols).copy()

print("Original shape :", df.shape)
print("Reduced shape  :", df_reduced.shape)

print("\nDropped columns:")
print(drop_cols)

Original shape : (7022, 32)
Reduced shape  : (7022, 28)

Dropped columns:
['mental_health_score', 'stress_vulnerability_score', 'academic_load_score', 'wellness_score']

In [37]:
# SAVING CLEANED DATASET --

from pathlib import Path

# current notebook folder
CURRENT_DIR = Path.cwd()

# notebooks folder
NOTEBOOKS_DIR = CURRENT_DIR.parent

# notebooks/preprocessed
PREPROCESSED_DIR = NOTEBOOKS_DIR / "preprocessed"
PREPROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Current Dir:", CURRENT_DIR)
print("Notebooks Dir:", NOTEBOOKS_DIR)
print("Preprocessed Dir:", PREPROCESSED_DIR)

Current Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\students_mental_health_survey
Notebooks Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks
Preprocessed Dir: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed

In [38]:
save_path = PREPROCESSED_DIR / "students_mental_health_survey_model_ready.csv"

df_reduced.to_csv(save_path, index=False)

print("Reduced / model-ready dataset saved successfully")
print("Saved at:", save_path)
print("Final shape:", df_reduced.shape)

Reduced / model-ready dataset saved successfully
Saved at: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed\students_mental_health_survey_model_ready.csv
Final shape: (7022, 28)